# Generated by Django 3.2.7 on 2021-10-18 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_spotifytoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='spotifyToken',
        ),
    ]
