# Generated by Django 3.2.7 on 2021-09-25 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbeats', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
