version: "3.9"

services:
  api:
    container_name: openbeats_442_api
    build:
      dockerfile: Dockerfile
      context: ./api
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: development
    ports:
      - 8000:8000

  postgres:
    container_name: openbeats_442_postgres
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db

  web:
    container_name: openbeats_442_web
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - "./web:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api

  pgadmin:
    container_name: openbeats_442_pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@openbeats716.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "80:80"
      - "5050:5050"
