import type { NextPage } from "next";
import Head from "next/head";
import CTA from "./cta/cta";
import Hero from "./hero/hero";
import Features from "./features/features";
import Footer from "./footer/footer";

const Home: NextPage = () => {
  return (
    <div className="relative bg-gray-800 overflow-hidden">
      <Head>
        <title>Open Beats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero></Hero>
      <Features></Features>
      <CTA></CTA>
      <Footer></Footer>
    </div>
  );
};

export default Home;
