# Generated by Django 3.2.7 on 2021-10-18 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_alter_spotifytoken_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifytoken',
            name='user',
        ),
    ]
